[version]
current = "0.1.0"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (
    (?P<lifecycle>a|b)
    (?P<release>\d*)
  )?
'''

[git]
message_template = "v{new_version}"
tag_template = "v{new_version}"

[[file]]
src = "setup.py"

[[file]]
src = "vyper_formatter.py"
